#!/usr/bin/env bash

readarray -t monData < <(
    hyprctl -j monitors | jq -r '
        .[] | select(.focused==true) | [
            .width,
            .height,
            (.scale|tostring|gsub("\\."; "")),
            .x,
            .y,
            .reserved[]
        ] | @tsv
    '
)
read -r mon_w mon_h mon_s mon_x mon_y mon_r0 mon_r1 mon_r2 mon_r3 <<< "${monData[0]}"
readarray -t curPos < <(hyprctl cursorpos -j | jq -r '.x,.y')


mon_w=$(( mon_w * 100 / mon_s ))
mon_h=$(( mon_h * 100 / mon_s ))
cur_x=$(( ${curPos[0]} - mon_x ))
cur_y=$(( ${curPos[1]} - mon_y ))

if (( cur_x >= mon_w / 2 )); then
    x_pos="east"
    x_off="-$(( mon_w - cur_x - mon_r2 ))"
else
    x_pos="west"
    x_off="$(( cur_x - mon_r0 ))"
fi

if (( cur_y >= mon_h / 2 )); then
    y_pos="south"
    y_off="-$(( mon_h - cur_y - mon_r3 ))"
else
    y_pos="north"
    y_off="$(( cur_y - mon_r1 ))"
fi

r_override="window{location:${x_pos} ${y_pos};anchor:${x_pos} ${y_pos};x-offset:${x_off}px;y-offset:${y_off}px;}"


if pgrep -x rofi > /dev/null; then
    killall rofi
    exit 0
fi

case "$1" in
    drun)
        rofi -no-config -no-lazy-grab -show drun -theme $HOME/.config/rofi/drun.rasi
        ;;
    clipboard)
        selection=$($HOME/.config/hypr/scripts/cliphist-img | rofi -no-config -no-lazy-grab -dmenu -i -p "" -show-icons -theme $HOME/.config/rofi/clipboard.rasi -theme-str "$r_override")
        [[ -z "$selection" ]] && exit 0
        $HOME/.config/hypr/scripts/cliphist-img "$selection"
        ;;
    wallpaper)
        $HOME/.config/hypr/scripts/wallpaper
        ;;
    *)
        echo "Usage: rofimenu [drun|clipboard|wallpaper]"
        exit 1
        ;;
esac

