#!/usr/bin/env bash

output_folder="$HOME/Pictures/Screenshots"
mkdir -p "$output_folder"
filename="$(date +'%Y-%m-%d_%H-%M-%S')_screenshot.png"

case "$1" in
    "region")
        hyprshot -m region -o "$output_folder" -f "$filename"
        ;;
esac
