preload = ~/Pictures/Wallpapers/macos-monterey-stock-black-dark-mode-layers-5k-6016x6016-5889.jpg
wallpaper =  eDP-1,~/Pictures/Wallpapers/macos-monterey-stock-black-dark-mode-layers-5k-6016x6016-5889.jpg
splash = false
