source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/windowrules.conf
source = ~/.config/hypr/conf.d/startup.conf
