exec-once = waybar
exec-once = swww-daemon
exec-once = swww img ~/Pictures/Wallpapers/wp.jpg
exec-once = nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
