windowrule = match:title ^(Open)$, float on
windowrule = match:title ^(Choose Files)$, float on
windowrule = match:title ^(Save As)$, float on
windowrule = match:title ^(Confirm to replace files)$, float on
windowrule = match:title ^(File Operation Progress)$, float on
windowrule = match:title ^(Properties)$, float on
windowrule = match:title ^(Progress)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Select files)$, float on
windowrule = match:title ^(Select a folder)$, float on
windowrule = match:title ^(Select a file)$, float on
windowrule = match:title ^(Select a directory)$, float on
windowrule = match:title ^(Select a file or directory)$, float on
windowrule = match:class ^(vivaldi-stable)$,match:title ^(Sign in - Google Accounts - Vivaldi)$, float on

windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(xdg-desktop-portal-kde)$, float on
windowrule = size 850 600, match:class ^(thunar)$, float on
windowrule = size 800 600, match:class ^(Spotify)$, float on
windowrule = match:class ^(kitty)$,match:title ^(top|btop|htop|gotop)$, float on
windowrule = match:class ^(vlc)$, float on
windowrule = match:class ^(mpv)$, float on
windowrule = match:class ^(kvantummanager|qt5ct|qt6ct|nwg-look)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol|pavucontrol)$, float on
windowrule = match:class ^(blueman-manager|nm-applet|nm-connection-editor)$, float on
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1|lxpolkit)$, float on
windowrule = match:class ^(Color Picker|org.gnome.font-viewer)$, float on

windowrule = match:title ^(Rename.*)$, float on, center on
windowrule = match:class ^(xarchiver)$,match:title ^(Create a new archive)$, float on, center on

windowrule = opacity 0.9 0.9,match:class ^(Cursor)$
windowrule = opacity 0.9 0.9,match:class ^(Code - Insiders)$
windowrule = opacity 0.9 0.9,match:class ^(kitty)$
windowrule = opacity 0.9 0.9,match:class ^(Spotify)$

# windowrule = match:class ^(vivaldi-stable)$, no_screen_share on
windowrule = match:tag private, no_screen_share on

windowrule = match:title ^(@.* - Discord)$, no_screen_share on


windowrule = match:class ^()$, match:title ^()$ , no_blur on
